Fix ctkDICOMObjectModel windows build error
This commit fixes a regression introduced in d8bbc43 (Fix some Qt5
component issues):

 C:\D\N\Slicer-0-build\CTK-build\CTK-build\Libs\DICOM\Widgets\moc_ctkDICOMObjectModel.cxx(55): error C2491: 'ctkDICOMObjectModel::staticMetaObjectExtraData' : definition of dllimport static data member not allowed