COMP: Fix Qt4/C++98 ctkDICOMBrowser build error due to protected signal
Fixes the following error:

  /path/to/CTK/Libs/DICOM/Core/ctkDICOMDatabase.h: In member function ‘void ctkDICOMBrowser::onRepairAction()’:
  /path/to/CTK/Libs/DICOM/Core/ctkDICOMDatabase.h:425:8: error: ‘void ctkDICOMDatabase::databaseChanged()’ is protected
     void databaseChanged();
          ^
  /path/to/CTK/Libs/DICOM/Widgets/ctkDICOMBrowser.cpp:928:37: error: within this context
     d->DICOMDatabase->databaseChanged();
                                       ^