Fix build of ctkTestApplication.cpp with Qt4. Fixes #482
This commit fixes windows build error originally introduced by
commit 77a4db54 adding support for Qt5.

Example of errors:

31>6>4>..\..\..\..\CTK\Libs\Widgets\ctkTestApplication.cpp(129) : error C2228: left of '.toLocal8Bit' must have class/struct/union
31>6>4>        type is 'const char *'