Add CTK_MSVC_ENABLE_MP to root CMakeLists and enable /MP /FS for MSVC
- Add global handling: if enabled (default ON) add /MP and /FS for MSVC or clang-cl frontend.
- Help mitigate PDB write conflicts on Windows (error C1090).