COMP: Fix Qt4/C++98 build using '> >' instead of '>>' in nested templates
This commit fixes build errors like the following:

  /path/to/CTK/Libs/DICOM/Core/ctkDICOMQuery.cpp:243:28: error: ‘>>’ should be ‘> >’ within a nested template argument list
   QList<QPair<QString,QString>> ctkDICOMQuery::studyAndSeriesInstanceUIDQueried()const
                              ^