COMP: Fix deprecated header check in Qt5
The QDesignerCustomWidgetInterface header was moved to QtUiPlugin/ in Qt5.5. This
commit fixes errors like the following when compiling with earlier
versions of Qt5:

CTK/Libs/Widgets/Plugins/ctkWidgetsAbstractPlugin.h:29:53: fatal error:
QtUiPlugin/QDesignerCustomWidgetInterface: No such file or directory