COMP: Fix build of plugin tests
This commit fixes a regression introduced in 8ec913626 (COMP: Fix Qt4
build adding fallback implementation for qUtf8Printable())

It addresses error like the following:

  In file included from /path/to/CTK/Libs/PluginFramework/ctkPluginConstants.h:27,
                   from /path/to/CTK/Plugins/org.commontk.eventadmin/Testing/Cpp/ctkEventAdminImplPerfTestMain.cpp:26:
  /path/to/CTK-build/CTK-build/Libs/PluginFramework/ctkPluginFrameworkExport.h:11:10: fatal error: ctkCompatibility_p.h: No such file or directory
     11 | #include "ctkCompatibility_p.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~