COMP: vtkDiscretizableColorTransferChart: Remove in-class initialization of non-const
This commit fixes error like this one:

```
error: ISO C++ forbids in-class initialization of non-const static member ‘rangeMoving’
```