COMP: Fix ctkVTKRenderView build error
This commit fixes a regression introduced in 2e78ec70 (COMP: Fix
-Wunused-parameter in ctkVTKRenderView::lookFromAxis()).

It addresses the following build error:

  /path/to/Slicer-Release/CTK/Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp: In member function ‘void ctkVTKRenderView::lookFromAxis(const ctkAxesWidget::Axis&, double)’:
  /path/to/Slicer-Release/CTK/Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp:499:26: error: call of overloaded ‘lookFromAxis(const ctkAxesWidget::Axis&)’ is ambiguous
    499 |   this->lookFromAxis(axis);
        |                          ^