COMP: Fix Qt4/C++98 ctkPythonConsole build by explicitly comparing with QChar
This commit fixes errors like the following introduced
in 08461b356 (ENH: Improve Python autocomplete list ordering)

Error:

  /path/to/CTK/Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp:379:18: error: conversion from ‘const char [2]’ to ‘QChar’ is ambiguous
       if (s1[0] != "_" && s2[0] == "_")
                    ^