Fix CTKDICOMWidgetsPythonQt windows build error undefining HAVE_INT64_T
This is a workaround to allow the build against DCMTK
version DCMTK-3.6.1_20150924 to succeed.

A more appropriate solution could be to update DCMTK so that it uses
namespaced macros like DCMTK_HAVE_INT64_T

This commit fixes the following build error:

//----
error C2146: syntax error : missing ';' before identifier 'Sint64'
C:\D\N\Slicer-1-build\DCMTK\ofstd\include\dcmtk/ofstd/oftypes.h(111) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
//----

See Slicer/Slicer#359

Reported-by: Andriy Fedorov <fedorov@bwh.harvard.edu>
Thanks: Andras Lasso <lasso@queensu.ca>